name: beerballer_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lottie: ^2.2.0
  onboarding: ^3.1.0
  animated_text_kit: ^4.2.1
  percent_indicator: ^4.2.2
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.0+1
  material_floating_search_bar: ^0.3.4
  url_launcher: ^6.0.10
  http: ^0.13.4
  flutter_form_builder: ^7.0.0
  intl: ^0.17.0
  flip_card: ^0.7.0
  scroll_snap_list: ^0.9.1
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.2
  provider: ^6.0.1
  flutter_spinkit: ^5.1.0
  google_sign_in: ^5.0.4
  firebase_core: ^2.5.0
  flutter_facebook_auth: ^5.0.7
  get: ^4.3.8
  image_picker: ^0.8.4+4
  mailer: ^6.0.0
  icon_shadow: ^1.0.1
  cached_network_image: ^3.2.0
  jiffy: ^5.0.0
  swipe_cards: ^2.0.0+1
  flutter_tindercard: ^0.2.0
  flutter_gifimage: ^1.0.1
  like_button: ^2.0.4
  gif_ani: ^0.0.2
  swipebuttonflutter: ^1.0.0
  async: ^2.8.2
  highlighter_coachmark: ^0.0.3
  tutorial_coach_mark: ^1.2.1
  lazy_load_scrollview: ^1.3.0
  video_player: ^2.4.7
  floating_frosted_bottom_bar: ^0.0.1
  kf_drawer: ^1.2.1
  flutter_zoom_drawer: ^3.0.2
  fancy_drawer: ^2.0.0
  easy_localization: ^3.0.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  widget_arrows: ^0.4.0
  firebase: ^9.0.3
  multi_select_flutter: ^4.1.2
  flutter_swipable: ^1.2.1
  swipe_deck: ^1.1.0
  appinio_swiper: ^1.1.0
  better_player: ^0.0.82
  emailjs: ^1.1.0
  open_mail_app: ^0.4.5
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/images/BeerBallerLogo_kleiner.png"
  android: true
  ios: true
  
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:

    - family: Roboto Condensed
      fonts:
        - asset: lib/assets/fonts/RobotoCondensed-Regular.ttf
    - family: Hubballi
      fonts:
        - asset: lib/assets/fonts/Shrikhand-Regular.ttf
  assets:
    - lib/assets/images/gutscheine.png
    - lib/assets/images/clothing.png
    - lib/assets/images/events.png
    - lib/assets/images/trinkspiele.png
    - lib/assets/images/beerpong.png
    - lib/assets/images/Header.png
    - lib/assets/images/Alle Spiele.png
    - lib/assets/images/wenig Material.png
    - lib/assets/images/Becherspiele.png
    - lib/assets/images/Würfelspiele.png
    - lib/assets/images/Kultspiele.png
    - lib/assets/images/Kartenspiele.png
    - lib/assets/images/blackCups.png
    - lib/assets/images/BeerBallerLogo_kleiner.png
    - lib/assets/images/schriftzug.png
    - lib/assets/images/beerNight.jpg
    - lib/assets/images/barBachelor.jpg
    - lib/assets/images/fromLeft.png
    - lib/assets/images/fromRight.png
    - lib/assets/images/BeerBallerSchriftzug.png
    - lib/assets/images/cardBackground.png
    - lib/assets/images/IconsInGame/swipe.png
    - lib/assets/images/IconsInGame/tap.png
    - lib/assets/images/Infopage/ricoflo.png
    - lib/assets/images//Infopage/groupPic.jpg
    - lib/assets/images/Infopage/models.jpg
    - lib/assets/images/Infopage/teamBildTische.jpg
    - lib/assets/images/facebook.png
    - lib/assets/images/googlePng.png
    - lib/assets/images/kreuz.png
    - lib/assets/images/schriftzugWeiß.png
    - lib/assets/images/orangeController.png
    - lib/assets/images/dice.png
    - lib/assets/images/cards.png
    - lib/assets/images/cups.png
    - lib/assets/images/kultGames.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
